---
- name: Start nginx
  service:
    name: nginx
    state: started

- name: Stop nginx
  service:
    name: nginx
    state: stopped

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
